name: Upload Website

on:
  push:
    branches:
    - main

jobs:

  ci:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: run lint on html
          run: npx --yes htmlhint "**/*.html"

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy static site to S3 bucket
      run: aws s3 sync . s3://www.alexcchip.com --delete